robot_radius: 1.0
transform_tolerance: 0.1
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 5.0
 raytrace_range: 3.0
 inflation_radius: 1.0
 track_unknown_space: false
 combination_method: 1

 observation_sources: laser_scan_sensor 
 laser_scan_sensor: {sensor_frame: lidar_wamv_link, data_type: LaserScan, topic: sensors/lidars/lidar/scan
, marking: true, clearing: true}
 #point_cloud_sensor: {sensor_frame: base_link, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  1  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     10.0   # max distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "map"

global_frame: map
robot_base_frame: base_link  
