GlobalPlanner:
  old_navfn_behavior: false
  use_quadratic: true
  use_dijkstra: true
  use_grid_path: false
  allow_unknown: true
  planner_window_x: 10.0
  planner_window_y: 10.0
  default_tolerance: 0.0
  publish_scale: 100

costmap: 
  footprint: [[-4, -2.4], [4, -2.4], [4, 2.4], [-4,2.4]]
  height: 100
  width: 100
  robot_radius: 7.0
  static_map: true
  
  inflation_layer:
    inflation_radius: 5
    cost_scaling_factor: 2
      #<remap from="global_planner/planner/plan" to="waypoints" />

