GlobalPlanner:
  old_navfn_behavior: false
  use_quadratic: true
  use_dijkstra: true
  use_grid_path: false
  allow_unknown: false
  planner_window_x: 10.0
  planner_window_y: 10.0
  default_tolerance: 3.0

  publish_scale: 100
  planner_costmap_publish_frequency: 0.0

  lethal_cost: 253                              # default 253
  neutral_cost: 50                              # default 50
  cost_factor: 5.0                            # Factor to multiply each cost from costmap by, default 3.0
  publish_potential: true                       # Publish Potential Costmap (this is not like the navfn pointcloud2 potential), default true


costmap: 
  footprint: [[-4, -2.4], [4, -2.4], [4, 2.4], [-4,2.4]]
  height: 100
  width: 100
  robot_radius: 7.0
  static_map: true
  
  inflation_layer:
    inflation_radius: 5
    cost_scaling_factor: 2
      #<remap from="global_planner/planner/plan" to="waypoints" />

